"""
Django settings for techno_chat project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", cast = str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast = bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backoffice_engine'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techno_chat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'backoffice_engine', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techno_chat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config("DATABASE_ENGINE", cast=str),
        'NAME': config("DATABASE_NAME", cast=str),
        'USER': config("DATABASE_USER", cast=str),
        'PASSWORD': config("DATABASE_PASSWORD", cast=str),
        'HOST': config("DATABASE_HOST", cast=str),
        'PORT': config("DATABASE_PORT", cast=str),
    }
}

AUTH_USER_MODEL = 'backoffice_engine.AdminUser'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "backoffice_engine", 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# The URL that the browser will use to access the files
MEDIA_URL = '/media/'

# The absolute physical path on your computer where Django will save the files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Logger Setup
LOG_DIR = BASE_DIR / "logs"
if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True, exist_ok=True)

LOG_FILE_MAX_SIZE_MB = config("LOG_FILE_MAX_SIZE_MB", cast=int)
LOG_FILE_BACKUP_COUNT = config("LOG_FILE_BACKUP_COUNT", cast=int)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "default": {
            "format": "[{asctime}] {levelname} {name} ({module}:{lineno}) {message}",
            "style": "{",
        },
    },

    "handlers": {
        "rotating_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs/log.log",
            "maxBytes": LOG_FILE_MAX_SIZE_MB * 1024 * 1024,
            "backupCount": LOG_FILE_BACKUP_COUNT,
            "formatter": "default",
            "encoding": "utf-8",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "default",
        },
    },

    "loggers": {
        "": {
            "handlers": ["rotating_file", "console"],
            "level": "DEBUG",
        },

        "django": {
            "handlers": ["rotating_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "django.request": {
            "handlers": ["rotating_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

logger = logging.getLogger(__name__)

# =========================================================
# DEBUG & TRACING
# =========================================================



LANGCHAIN_API_KEY = config("LANGCHAIN_API_KEY", cast = str)
LANGCHAIN_PROJECT = config("LANGCHAIN_PROJECT", cast = str)
LANGCHAIN_TRACING_V2 = config("LANGCHAIN_TRACING_V2", "false").lower() == "true"
os.environ["LANGCHAIN_API_KEY"] = LANGCHAIN_API_KEY
os.environ["LANGCHAIN_PROJECT"] = LANGCHAIN_PROJECT
os.environ["LANGCHAIN_TRACING_V2"] = "true" if LANGCHAIN_TRACING_V2 else "false"

# =========================================================
# TEXT SPLITTER
# =========================================================

TEXT_SPLITTER_CHUNK_SIZE = config("TEXT_SPLITTER_CHUNK_SIZE", cast = int)
TEXT_SPLITTER_CHUNK_OVERLAP_SIZE = config("TEXT_SPLITTER_CHUNK_OVERLAP_SIZE", cast = int)

# =========================================================
# PINECONE
# =========================================================

PINECONE_API_KEY = config("PINECONE_API_KEY", cast = str)
PINECONE_HOST_URL = config("PINECONE_HOST_URL", cast = str)

PINECONE_NAMESPACE = config("PINECONE_NAMESPACE", cast = str)

PINECONE_DENSE_EMBEDDING_MODEL = config("PINECONE_DENSE_EMBEDDING_MODEL", cast = str)
PINECONE_SPARSE_EMBEDDING_MODEL = config("PINECONE_SPARSE_EMBEDDING_MODEL", cast = str)
PINECONE_RERANK_MODEL = config("PINECONE_RERANK_MODEL", cast = str)

PINECONE_UPSERT_BATCH_SIZE = config("PINECONE_UPSERT_BATCH_SIZE", cast = int)
PINECONE_EMBED_BATCH_SIZE = config("PINECONE_EMBED_BATCH_SIZE", cast = int)

# =========================================================
# RETRIEVAL
# =========================================================

RETRIEVAL_TOP_K = config("RETRIEVAL_TOP_K", cast = int)
RERANK_TOP_N = config("RERANK_TOP_N", cast = int)
RET_SUMMARY_TOP_K = config("RET_SUMMARY_TOP_K", cast = int)
RE_SUMMARY_TOP_N = config("RE_SUMMARY_TOP_N", cast = int)

# =========================================================
# GROQ
# =========================================================

GROQ_API_KEY = config("GROQ_API_KEY", cast = str)

GROQ_LLM_MODELS = {
    "Llama 3.3 70B": config("GROQ_MODEL_LLAMA_70B", cast = str),
    "Llama 3.1 8B": config("GROQ_MODEL_LLAMA_8B", cast = str),
    "GPT OSS 120B": config("GROQ_MODEL_GPT_OSS", cast = str),
}

GROQ_CHAT_COMPLETION_TEMPERATURE = config("GROQ_CHAT_COMPLETION_TEMPERATURE", cast = float)

# =========================================================
# GOOGLE GEMINI
# ========================================================

GOOGLE_API_KEY = config("GOOGLE_API_KEY", cast = str)

GEMINI_LLM_MODELS = {
    "Gemini 2.5 Pro": config("GEMINI_MODEL_PRO", cast = str),
    "Gemini 2.5 Flash": config("GEMINI_MODEL_FLASH", cast = str),
    "Gemini 2.5 Flash-Lite": config("GEMINI_MODEL_FLASH_LITE", cast = str),
}

GOOGLE_CHAT_COMPLETION_TEMPERATURE = config("GOOGLE_CHAT_COMPLETION_TEMPERATURE", cast = float)

VLM_MODEL = config("IMAGE_MODEL", cast = str)

# =========================================================
# MODEL MAP
# =========================================================

MODEL_MAP = {**GROQ_LLM_MODELS, **GEMINI_LLM_MODELS}

# =========================================================
# LOGGERS
# =========================================================
LOG_FILE_MAX_SIZE_MB = config("LOG_FILE_MAX_SIZE_MB", cast = int)
LOG_FILE_BACKUP_COUNT = config("LOG_FILE_BACKUP_COUNT", cast = int)

# =========================================================
# WEB SEARCH (SERPER.DEV)
# =========================================================
SERPER_API_KEY    = config('SERPER_API_KEY', cast=str)
SERPER_MAX_RESULTS = config('SERPER_MAX_RESULTS', default=6, cast=int)
SERPER_ENDPOINT   = config('SERPER_ENDPOINT', cast=str)

# =========================================================
# AI ASSISTANT MODE
# =========================================================
AI_ASSISTANT_SYSTEM_PROMPT = config('AI_ASSISTANT_SYSTEM_PROMPT', cast=str)

# =========================================================
# KIE IMAGE
# =========================================================
KIE_API_KEY = config('KIE_API_KEY', cast=str)

OPENAI_TEXT_IMAGE_MODEL = config('OPENAI_TEXT_IMAGE_MODEL', cast=str)
OPENAI_IMAGE_MODEL = config('OPENAI_IMAGE_MODEL', cast=str)

# =========================================================
# RAG ANSWER IMAGES / PAGE VIEWER
# =========================================================
PAGE_RENDER_DPI    = config('PAGE_RENDER_DPI', default=150, cast=int)
PAGE_RENDER_FORMAT = config('PAGE_RENDER_FORMAT', default='png', cast=str)

